import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import {
  bumpPackageVersion,
  cargoLockPath,
  createManualBumpBranchName,
  packageManifestPaths,
  readCargoLockWorkspacePackageVersions,
  readCargoTomlPackageVersion,
  rustCrateManifestPaths,
  rustCrateNames,
  versionFilePaths,
} from "../scripts/bump-release-version.mjs";

const projectRoot = fileURLToPath(new URL("..", import.meta.url));

const rustCrateNameByManifestPath = new Map([
  ["crates/maximus-cli/Cargo.toml", "maximus-cli"],
  ["crates/maximus-core/Cargo.toml", "maximus-core"],
  ["crates/maximus-checks/Cargo.toml", "maximus-checks"],
]);

async function writeJson(filePath, value) {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

async function writeReleaseVersionFixture(repoRoot, lockPackageNames = rustCrateNames) {
  await writeJson(path.join(repoRoot, "package.json"), {
    name: "@jeremyfellaz/maximus",
    version: "0.1.0",
    optionalDependencies: {
      "@jeremyfellaz/maximus-darwin-arm64": "0.1.0",
      "@jeremyfellaz/maximus-darwin-x64": "0.1.0",
      "@jeremyfellaz/maximus-linux-arm64-gnu": "0.1.0",
      "@jeremyfellaz/maximus-linux-x64-gnu": "0.1.0",
    },
  });

  for (const relativePath of packageManifestPaths.slice(1)) {
    await writeJson(path.join(repoRoot, relativePath), {
      name: `pkg-${relativePath}`,
      version: "0.1.0",
    });
  }

  for (const relativePath of rustCrateManifestPaths) {
    await mkdir(path.dirname(path.join(repoRoot, relativePath)), { recursive: true });
    await writeFile(
      path.join(repoRoot, relativePath),
      `[package]\nname = "${rustCrateNameByManifestPath.get(relativePath)}"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nfixture-dep = { version = "9.9.9" }\n`,
      "utf8",
    );
  }

  const lockPackages = lockPackageNames
    .map(
      (packageName) =>
        `[[package]]\nname = "${packageName}"\nversion = "0.1.0"\n`,
    )
    .join("\n");
  await writeFile(
    path.join(repoRoot, cargoLockPath),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "fixture-dep"\nversion = "9.9.9"\n\n${lockPackages}`,
    "utf8",
  );
}

test("bumpPackageVersion updates root and platform package manifests together", async () => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "maximus-bump-version-"));
  await writeReleaseVersionFixture(repoRoot);

  const result = await bumpPackageVersion("v0.1.1", repoRoot);
  assert.equal(result.version, "0.1.1");
  assert.equal(result.tag, "v0.1.1");
  assert.equal(result.manifestPaths.length, packageManifestPaths.length);

  for (const relativePath of packageManifestPaths) {
    const manifest = JSON.parse(await readFile(path.join(repoRoot, relativePath), "utf8"));
    assert.equal(manifest.version, "0.1.1");
  }

  const rootManifest = JSON.parse(await readFile(path.join(repoRoot, "package.json"), "utf8"));
  assert.deepEqual(Object.values(rootManifest.optionalDependencies), [
    "0.1.1",
    "0.1.1",
    "0.1.1",
    "0.1.1",
  ]);
});

test("bumpPackageVersion updates all version files including Rust crates and Cargo.lock", async () => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "maximus-bump-version-full-"));
  await writeReleaseVersionFixture(repoRoot);

  const result = await bumpPackageVersion("v0.1.1", repoRoot);
  assert.deepEqual(
    versionFilePaths,
    [...packageManifestPaths, ...rustCrateManifestPaths, cargoLockPath],
  );
  assert.equal(result.versionFilePaths.length, versionFilePaths.length);

  for (const relativePath of rustCrateManifestPaths) {
    const cargoToml = await readFile(path.join(repoRoot, relativePath), "utf8");
    assert.equal(readCargoTomlPackageVersion(cargoToml, relativePath), "0.1.1");
    assert.match(cargoToml, /fixture-dep = \{ version = "9\.9\.9" \}/);
  }

  const cargoLock = await readFile(path.join(repoRoot, cargoLockPath), "utf8");
  assert.deepEqual(readCargoLockWorkspacePackageVersions(cargoLock, rustCrateNames), {
    "maximus-checks": "0.1.1",
    "maximus-cli": "0.1.1",
    "maximus-core": "0.1.1",
  });
  assert.match(cargoLock, /name = "fixture-dep"\nversion = "9\.9\.9"/);
});

test("bumpPackageVersion fails closed when Cargo.lock is missing a workspace package block", async () => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "maximus-bump-version-missing-lock-"));
  await writeReleaseVersionFixture(repoRoot, ["maximus-cli", "maximus-checks"]);

  await assert.rejects(
    bumpPackageVersion("v0.1.1", repoRoot),
    /Cargo\.lock package block not found for maximus-core/,
  );

  const rootManifest = JSON.parse(await readFile(path.join(repoRoot, "package.json"), "utf8"));
  assert.equal(rootManifest.version, "0.1.0");
  const cliCargoToml = await readFile(path.join(repoRoot, "crates/maximus-cli/Cargo.toml"), "utf8");
  assert.equal(readCargoTomlPackageVersion(cliCargoToml, "crates/maximus-cli/Cargo.toml"), "0.1.0");
});

test("bumpPackageVersion fails closed when a Cargo.lock workspace version line is malformed", async () => {
  const repoRoot = await mkdtemp(path.join(os.tmpdir(), "maximus-bump-version-malformed-lock-"));
  await writeReleaseVersionFixture(repoRoot);
  const cargoLock = await readFile(path.join(repoRoot, cargoLockPath), "utf8");
  await writeFile(
    path.join(repoRoot, cargoLockPath),
    cargoLock.replace(
      'name = "maximus-cli"\nversion = "0.1.0"',
      'name = "maximus-cli"\nversion = "0.1.0" trailing',
    ),
    "utf8",
  );

  await assert.rejects(
    bumpPackageVersion("v0.1.1", repoRoot),
    /Cargo\.lock package block for maximus-cli has an invalid version/,
  );

  const rootManifest = JSON.parse(await readFile(path.join(repoRoot, "package.json"), "utf8"));
  assert.equal(rootManifest.version, "0.1.0");
  const coreCargoToml = await readFile(path.join(repoRoot, "crates/maximus-core/Cargo.toml"), "utf8");
  assert.equal(readCargoTomlPackageVersion(coreCargoToml, "crates/maximus-core/Cargo.toml"), "0.1.0");
});

test("createManualBumpBranchName is deterministic per tag and base", () => {
  assert.equal(
    createManualBumpBranchName("v0.1.1", "master"),
    createManualBumpBranchName("v0.1.1", "master"),
  );
  assert.notEqual(
    createManualBumpBranchName("v0.1.1", "master"),
    createManualBumpBranchName("v0.1.2", "master"),
  );
});

test("bump module can be imported from node eval with tag argv", () => {
  const output = execFileSync(
    process.execPath,
    [
      "--input-type=module",
      "-e",
      "import { createManualBumpBranchName } from './scripts/bump-release-version.mjs'; console.log(createManualBumpBranchName(process.argv[1]));",
      "v0.1.1",
    ],
    { cwd: projectRoot, encoding: "utf8" },
  );

  assert.match(output, /^codex\/manual-bump-master-v0-1-1-[0-9a-f]{8}\n$/);
});
